<!doctype html>
<html>
<?php include "bundling.php" ?>

<body>
    <?php include "header.php"; ?>
    <section class="prelogin-wrapper">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="pre-login tnc">
                        <h2>Master Campaign Agreement</h2>
                        <h3>1. Introduction</h3>
                        <p>1.1 This ”Master Campaign Agreement” together with Schedule 1 and any applicable EIOs (collectively the “Agreement”) is between you, hereinafter referred to as “Advertiser” and/or “Media Partner” (each a “Participant”) to utilize the platform currently located at www.impact.com (the “Platform”) owned and operated by Impact Tech, Inc. (“Impact”).
                        1.2 The Participants shall agree to specific terms of engagement in individual “Electronic Insertion Order(s)” (“EIO”). EIOs contain any supplemental terms and conditions agreed between the Participants and are created using the “Insertion Order” function on the Platform. The EIOs shall specify the actions (“Actions”) and qualifying parameters that entitle Media Partner to compensation from the Advertiser (“Payouts”). Impact shall be a facilitator for the relationship between Advertisers and Media Partners and shall not be an active party to the Agreement. Accordingly, the terms of the EIOs are strictly between Media Partner and Advertiser.
                        </p>

                        <h3>2. Entering into Electronic Insertion Orders</h3>
                        <p>2.1 The Participants acknowledge and agree that: either Participant may propose an EIO in the “Insertion Order” section of the Platform interface and that the Platform’s functionality may then be used by either of them to decline, retract or further modify an EIO before acceptance. If the parties utilize other forms of insertion orders, then Schedule 1 must reflect this occurrence and the Participants are responsible for implementing the appropriate settings on the Platform to conform with such agreed upon terms. <br>
                        2.2 Media Partner makes no guarantee or representation that it will generate any Action(s). Except as provided for in any EIO, if at all, Advertiser makes no guarantee or representation that the Media Partner will be successful in earning any Payouts.</p>

                        <h3>3. Term and Termination</h3>
                        <p>
                            3.1 EIOs: Each individual EIO shall continue until the earlier of: (a) the expiration of it; or (b) a Participant terminating the EIO pursuant to the terms of the Agreement. <br>
                            3.2 Consequences of Termination: On the expiration or earlier termination of each EIO:<br>
                            (a) the Media Partner shall refund the Advertiser any monies, if any, in relation to unfulfilled obligations that the Advertiser has paid the Media Partner in advance in relation to an EIO;<br>
                            (b) the Advertiser shall remain obligated to compensate the Media Partner for Payouts earned prior to the expiration or termination of the EIO;<br>
                            (c) the Media Partner shall immediately discontinue the use of any materials provided by the Advertiser (the “Creative”);<br>
                            (d) license to the Creative shall terminate; and <br>
                            (e)each Participant shall either destroy or promptly return to the other Participant all copies in whatever medium of the other’s Confidential Information.
                        </p>

                        <h3>4. Intellectual Property and Confidential Information</h3>
                        <p>
                        4.1 License. Pursuant to the terms herein, the Advertiser grants to the Media Partner for the duration of each EIO a revocable, non‑exclusive, non-transferable, world-wide, royalty-free license to use the Creative solely to the extent necessary to perform its obligations herein. <br>
                        4.2 Promotional Methods. Unless explicitly authorized in an EIO, Media Partner shall not promote a Creative using the following means:<br>
                        (a) provision of leads obtained other than through intended consumer (“End User”) action (e.g. through the use of phone books, or similar such compilations of personal data);<br>
                        (b) use of fake redirects, automated software, or other mechanisms to generate Actions;<br>
                        (c) Actions that are not in good faith, such as those using any automated device, robot, Iframes or hidden frames; or <br>
                        (d) the use of incentives to procure Actions from End Users. <br>
                        4.3 Intellectual Property: “Intellectual Property” means trade marks (whether registered or unregistered together with all goodwill in connection thereto), unregistered and registered designs, copyright, database rights, rights in computer software, domain names, rights in Confidential Information and all other intellectual property rights (whether now subsisting or in the future created). All Intellectual Property existing prior to the commencement date of each EIO shall belong to the Participant that owned such rights immediately prior to such date. Each Participant acknowledges and agrees that it shall not acquire or claim any title to the other Participant’s Intellectual Property. <br>
                        4.4 Confidential Information. "Confidential Information" means all confidential information and data, whether in tangible or intangible form such as trade secrets, financial, and technical information, customers, prices, discounts, and margins. A Participant receiving Confidential Information ("Receiving Party") from the other Participant ("Disclosing Party") agrees to (a) hold all Confidential Information in confidence and protect it with the same degree of care with which the Receiving Party protects its own Confidential Information; (b) use such Confidential Information only for the purposes of this Agreement and as permitted by this Agreement; (c) not copy or otherwise duplicate such Confidential Information, except for the purpose of this Agreement; and (d) restrict disclosure of such Confidential Information solely to those employees and agents with a need to know such Confidential Information for the purposes of this Agreement and who are bound in writing to protect the same. The foregoing obligations shall not apply to any information designated as confidential if, prior to any release of such information, such Confidential Information: was already known to the Receiving Party, free of any obligation to keep it confidential; is or becomes publicly known through no wrongful act of the Receiving Party; is independently developed by the Receiving Party without reference to the Confidential Information of the Disclosing Party; was received from a third party without any restriction on confidentiality; was disclosed to third parties by the Disclosing Party without any obligation of confidentiality; or is approved for release by prior written authorization of the Disclosing Party. If the Receiving Party receives a request pursuant to a court order, governmental body request or other legal process to disclose the Disclosing Party's Confidential Information, the Receiving Party shall promptly notify the Disclosing Party and reasonably assist the Disclosing Participant in obtaining a protective order requiring that any portion of the Confidential Information required to be disclosed be used only for the purpose for which a court issues an order or as otherwise required by law. Each Participant shall bear its own legal expenses in connection therewith
                        </p>

                        <h3>5. Representations, Disclaimers and Indemnification</h3>
                        <p>5.1 Representations and Warranties: <br>
                            (a) Each Participant warrants, represents and undertakes that: <br>
                            (i) it has the full power and authority to carry out its obligations in the Agreement; <br>
                            (ii) its entry into and performance of its obligations under the Agreement shall not infringe the rights of any third party or cause it to be in breach of any obligations to a third party; <br>
                            (iii) it shall comply fully with any and all applicable laws, rules and regulations in its performance under the Agreement.
                            5.2 Indemnification: Each Participant ("Indemnitor") shall defend, indemnify and hold the other Participant and its respective shareholders, directors, officers, employees, subcontractors and agents ("Indemnitee") harmless against all claims, suits, costs, damages liabilities, expenses (including reasonable attorney's fees), settlements and judgments incurred, claimed or sustained by third parties (“Claims”) for the Indemnitor's breach of this Agreement, provided that: (a) Indemnitee notifies Indemnitor in writing within a commercially reasonable time after its receipt of notice of any Claim; (b) Indemnitor has sole control of the defense and all related settlement negotiations (except that the Indemnitor shall not settle any Claim in any manner which would admit fault by the Indemnitee without Indemnitee’s reasonable consent); and (c) Indemnitee provides Indemnitor with reasonable assistance, information and authority necessary to perform its obligations under this Section. Indemnitee may participate in the defense of a Claim at Indemnitee’s expense, and such participation shall not waive or reduce any obligations on the Indemnitor under this Section.
                            5.3 Limitations of Liability: <br>
                            (a) Nothing below shall operate to exclude or limit liability for which liability cannot be excluded or limited under law (together the "Excluded Losses"). <br>
                            (b) Except in respect of the Excluded Losses, the liability of each Party to any other Party in contract, tort (including negligence or breach of statutory duty, misrepresentation or otherwise) or for any other common law or statutory cause of action or otherwise arising by reason of or in connection with this Agreement and each EIO shall be limited to the Payouts fees paid by Advertiser to Media Partner through Impact pursuant to EIOs. <br>
                            (c) Except in respect of the Excluded Losses, neither Party shall be liable to the other in contract, tort (including negligence) or otherwise for any: any loss of actual or potential profits, contracts or customers; loss of data and undertaking data or other restoration; loss of reputation; any other indirect, consequential, special, punitive, exemplary damages whether arising from negligence, breach of contract or otherwise.
                        </p>

                        <h3>6. General</h3>
                        <p>6.1 Waiver of Remedies: No forbearance or delay by either Participant in exercising or enforcing the provisions of this Agreement shall prejudice or restrict the rights of that Participant nor shall any waiver of its rights operate as a waiver of any subsequent breach. No right, power or remedy herein conferred upon or reserved for either Participant or available by law is exclusive of any other right, power or remedy available to that Participant and each such right, power or remedy shall be cumulative. <br>
                        6.2 Assignment: Either Participant may assign any or all of its rights under this Agreement, or transfer or sub-contract any or all of its obligations under this Agreement, upon notification to the other Participant, subject to the non-assigning Participant’s right to terminate. <br>
                        6.3 Audit rights: Each Participant agrees to maintain adequate books and records relating to its compliance with the terms of this Agreement during the term of this Agreement and for a period of one (1) year thereafter. Copies of such records shall be made available to the other Participant upon written request. <br>
                        6.4 Notices: All notices which are required to be given under this Agreement shall be in writing. Notices of termination of an EIO by Advertiser for convenience shall be made via the Platform. All other notices shall be sent to the postal address or facsimile number of the Participant as provided via the Platform, as such address may be updated from time to time. Any such notice may be delivered personally or by first class pre-paid letter (or by air-mail if overseas) or by facsimile transmission, and shall be deemed received, when delivered (if by hand); or if by mail five (5) days after deposit in mail, if by facsimile transmission, when successfully dispatched in full.
                        </p>

                        <h3>7. General</h3>
                        <p>
                        7.1 Force Majeure: "Force Majeure" means circumstances beyond the reasonable control of a Participant, including but not limited to acts of God, war, terrorist action, fire, flood, governmental act Internet or other telecommunications failure. Neither Participant shall be liable to the other Participant for any failure or delay in performing any of its obligations hereunder if such failure or delay is caused by the occurrence of an event of Force Majeure. If a Participant becomes aware of a Force Majeure event, such Participant shall immediately notify the other Participant in writing. If the event of Force Majeure continues period in excess of three (3) weeks, then either Participant may terminate this Agreement by written notice to the other Participant with immediate effect. <br>
                        7.2 Entire Agreement: This Agreement represents the entire understanding and constitutes the entire agreement in relation to the subject matter herein, it supersedes any previous agreement as to such subject matter herein, and may be amended only in writing and executed by both parties. Each party acknowledges and agrees that it has not relied on any representation or warranty other than those expressly set out herein. <br>
                        7.3 Electronic Signatures: Each party acknowledges and agrees that by clicking-through acceptance of this Agreement; it is submitting an authorized electronic signature and entering into a legally binding contract. Further, each party hereby waive any rights or requirements under any applicable statutes, regulations, rules, ordinances or other laws in any jurisdiction which require an original signature or delivery or retention of non-electronic records, or to payments or the granting of credits by other than electronic means. <br>
                        7.4 Severability: If any provision in this Agreement, in whole or in part, held by a court or administrative body of competent jurisdiction to be illegal, invalid or unenforceable under any enactment or rule of law then that provision or part shall be deemed not to form part of this Agreement and the enforceability and validity of the remainder of this Agreement shall not be affected. The parties shall in good faith attempt to modify any invalidated provision or part to carry out the parties' stated intentions. <br>
                        7.5 Survival: All provisions that by their nature should reasonably be interpreted to survive the termination or expiration of this Agreement, shall survive such termination or expiration of this Agreement. <br>
                        7.6 Relationship of the Parties: The relationship of the Participants is that of independent contractors and this Agreement does not create any association, partnership, joint venture or agency relationship between them. Neither Participant shall have the power to bind the other or to create a liability against the other in any way.
                        </p>

                        <h2>Schedule 1</h2>
                        <h3>General Terms and Conditions</h3>
                        <p>This Schedule 1 applies as between Advertiser and Media Partner unless superseded in whole or part by written agreement executed between them. <br>
                        1. Tracking Actions and Calculating Payouts: Unless an EIO states otherwise, all tracking and payment processing facilities in relation to the tracking of Actions and calculation of Payouts shall be provided by Impact. Impact shall aggregate payments due from Advertisers to the Media Partner and make payments to the Media Partner in accordance with each EIO. If tracking is disabled as a result of the Advertiser’s acts or omissions and the Advertiser continues to receive traffic from the Media Partner then the Advertiser shall be obliged to pay Payouts on a fair and reasonable basis taking into account appropriate factors. <br>
                        2. Chargebacks: Actions can be cancelled or returned by the Advertiser (“Chargeback”) if: (a) an Action is incomplete; (b) if a customer has cancelled or returns an Action; (c) if an Action has been made fraudulently or in an otherwise non-bona fide manner; (d) if an Action is carried out by a person who is outside the area serviced by the Advertiser; or (e) if the Advertiser is unable to ship goods to a customer in relation to an Action. Each EIO shall state the period of time within which the Advertiser may apply a Chargeback. <br>
                        3. Governing Law and Venue: Unless the Parties mutually agree otherwise in writing, this Agreement, Schedule 1 and each EIO shall be governed by the laws of the State of California and such state shall be the sole and exclusive forum or any disputes under this Agreement. A Participant that primarily prevails in an action brought under this Agreement is entitled to recover from the other Participant its reasonable attorneys' fees and costs.</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <?php include "footer.php"; ?>
</body>

</html>