<!DOCTYPE html>
<html lang="en">
<head>
    <?php include "bundling.php"; ?>
</head>
<body>
    <?php include "header.php" ?>
    <section class="innerpage-banner clearfix" style="background-image:url(assets/innerpage-banner/termsofuse.jpg);">
        <div class="transparent-layer">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-12 innerpage-bannner-content">
                        <h1>Terms of Use</h1>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="innerpage-content clearfix">
        <div class="container">
                <div class="row">
                    <div class="col-sm-12 col-md-12 col-lg-12 leftContent slideInUp">
                        <h2>Disclaimer / Terms of Use</h2>
                        <p>This website (the “Site”) is the website of Hoque Global (“Hoque Global”, “us” or “we”). The pages or tabs on this Site are published by our partner on behalf of Hoque Global. We reserve the right to vary the conditions of use at any time. Before using this website, please read the following terms of use and disclaimers. </p>
                        <h3>Acceptance of terms</h3>
                        <p>Hoque Global maintains this Website (the "Site") for your personal usage. Your privileges, utilization, and access of this Site are subject to the following Terms of Use. Hoque Global reserves the right to update these Terms of Use at any time without notice to you. The most current version of the Terms of Use may be accessed by clicking on the "Terms of Use" hypertext link located at the bottom of the Site. Please read the terms and conditions below as by using this Site, you accept, without limitation or qualification, these Terms of Use and to be bound by them. If you do NOT agree to these Terms of Use, DO NOT USE THIS SITE. You are recommended to review these terms of use on a regular basis as you will be presumed to have accepted variations and discrepancies if you continue to use the Site after they have been posted.</p>
                        <h3>The accuracy of information provided</h3>
                        <p>To the best of its ability, Hoque Global makes sure to take precaution and confirm that the information contained in this Site is accurate, reliable, and updated. Information published on the Site is supplied by Hoque Global and, where indicated, may be by certain third parties. However, Hoque Global makes no warranties or representations as to the accuracy, correctness, reliability or otherwise with respect to such information. Hoque Global cannot promise or be held liable for the complete accuracy of information provided here or for the timeliness in the change of information provided here. Hoque Global shall edit information on the site when necessary and reserves the right to make these changes without the obligation to alert or notify all current, future, or past visitors of the site. Any alterations or improvements in any products or services on this Site shall be made at any time without needing to notify anyone.
The information presented in this Site is not investment advice and shall under no circumstances constitute an offer or solicitation to buy or sell anything. None of the information on this Site shall be taken as any type of advice. The information presented on this site does not indicated that any other products, services or otherwise deals in these or enter into a contract with Hoque Global or any other company. Finally, the information on this Site shall not be depended on or in links with any investment decision. 
</p>
                        <p>As a visitor of this website, you shall not depend on the information provided on this Site. You should be advised to take the appropriate measures to verify the information presented here before acting on it. Hoque Global also assumes no liability or responsibility for any omissions or errors in the content of this Site.</p>
                        <h3>Visitor/Your use of the Site + Copyright Notice</h3>
                        <p>Hoque Global owns the copyright of the design and architecture of the Site as well as the copyright in the content presented on the Site unless noted otherwise indicated by a third party's proprietary notice. Any Images, videos, trademarks and brands are also protected by other intellectual property laws and must not be reproduced or appropriated in any other manner without written permission of their respective owners. Unless specifically prohibited by a notice published on any page, you may make a print copy of such parts of the Site as you may reasonably require for your own personal use provided that any copy has attached to it any relevant proprietary notices and/or disclaimers. You may download content for non-commercial, personal use only, provided copyright, trademark or other proprietary notices remain unchanged and visible. No right, title or interest in any downloaded materials is transferred to you as a result of any such downloading or copying. You agree that you will not otherwise copy, modify, alter, display, distribute, sell, broadcast or transmit any material on the Site in any manner without the written permission of Hoque Global. All other use is prohibited. Hoque Global is not responsible for the content of any other website from which you have accessed this Site or to which you may hyperlink from the website and cannot be held liable for any loss or damage you incur as a result thereof. To the extent that any part of these conditions of use is found to be invalid, unlawful or unenforceable by any court of competent jurisdiction such part shall to that extent be severed from the remaining terms all of which shall remain in full force and effect as permitted by law.</p>
                        <p>Per condition of your use of the Site, you shall not use the Site for any purpose or reason that is unlawful or prohibited by these Terms of Use or any applicable laws.</p>
                        <p>Unless otherwise noted, the graphic images, videos,  buttons and text contained in this Site are the exclusive property of Hoque Global and its subsidiaries. Except for personal use, these items may not be copied, distributed, displayed, reproduced, or transmitted, in any form or by any means, electronic, mechanical, photocopying, recording, or otherwise without prior written permission of Hoque Global.</p>
                        <h3>Disclaimer</h3>
                        <p>HOQUE GLOBAL PUBLISHED/ES THE WEBSITE ON AN “AS IS” BASIS WITHOUT ANY WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF THE WEBSITE, THE ACCURACY OF THE INFORMATION OR THE PRODUCTS OR SERVICES REFERRED TO ON THE WEBSITE (IN SO FAR AS SUCH WARRANTIES MAY BE EXCLUDED UNDER ANY RELEVANT LAW) AND TO THE EXTENT PERMITTED BY LAW, HOQUE GLOBAL SHALL NOT BE LIABLE FOR ANY LOSSES OR DAMAGE WHETHER DIRECT OR INDIRECT (INCLUDING, WITHOUT LIMITATION DIRECT OR INDIRECT LOSS OF PROFITS), CONSEQUENTIAL, SPECIAL OR OTHERWISE INCIDENTAL THAT MAY RESULT FROM USE OF THE WEBSITE HOWSOEVER ARISING. HOQUE GLOBAL DISCLAIMS ALL RESPONSIBILITY FOR ANY LOSS, INJURY, CLAIM, LIABILITY OR DAMAGE OF ANY KIND RESULTING FROM, ARISING OUT OF OR ANY WAY RELATED TO (A) ANY ERRORS IN OR OMISSIONS FROM THIS WEBSITE AND THE CONTENT, INCLUDING BUT NOT LIMITED TO TECHNICAL INACCURACIES AND TYPOGRAPHICAL ERRORS, (B) ANY THIRD PARTY WEB SITES OR CONTENT THEREIN DIRECTLY OR INDIRECTLY ACCESSED THROUGH LINKS IN THIS WEBSITE, INCLUDING BUT NOT LIMITED TO ANY ERRORS IN OR OMISSIONS THEREFROM, (C) THE UNAVAILABILITY OF THE WEBSITE OR ANY PORTION THEREOF, (D) YOUR USE OF THIS WEBSITE OR (E) YOUR USE OF ANY EQUIPMENT OR SOFTWARE IN CONNECTION WITH THE WEBSITE. HOQUE GLOBAL IS NOT RESPONSIBLE FOR ANY WARRANTIES INCLUDING THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT.</p>
                        <h3>Limitation of liability</h3>
                        <p>Under not any legal theory and under no event in any manner or form (whether in tort, contract, strict liability or otherwise) shall Hoque Global be liable for any direct, indirect, special, incidental or consequential damages arising out of any use of the information contained herein, including, without limitation, damages for lost profits, loss of goodwill, loss of data, work stoppage, accuracy of results, or computer failure or malfunction.</p>
                        <h3>Indemnification</h3>
                        <p>You agree to defend, indemnify and hold Hoque Global harmless from and against any and all claims, damages, costs and expenses, including attorney's fees, arising from and related to your use of the Site.</p>
                        <h3>Trademarks</h3>
                        <p>This Site features logos, brand identities and other trademarks and service marks (collectively, the "Marks") that are the property of, or are licensed to Hoque Global and its subsidiaries. Nothing contained on this Site should be construed as granting, by implication, estoppel, or otherwise, any license or right to use any Mark displayed on this Site without written permission of Hoque Global or any such third party that may own a Mark displayed on the Site.</p>
                        <h3>Links to third-party sites</h3>
                        <p>As a convenience to users, this Site may link to other sites owned and operated by third parties and not maintained by Hoque Global. However, even if such third parties are affiliated with Hoque Global, Hoque Global has no control over these linked sites, all of which have separate privacy and data collection practices and legal policies independent of Hoque Global. Hoque Global is not responsible for the contents of any linked sites and does not make any representations regarding the content or accuracy of material on such sites. Viewing such third party sites is entirely at your own risk.</p>
                        <h3>Jurisdiction</h3>
                        <p>Hoque Global maintains, published, and operates this Site. By using this site you consent to the jurisdiction of the courts for any action arising from these Terms of Use. Any cause of action or claim you may have with respect to the Site must be commenced within one (1) year after the claim or cause of action arises. If any portion of these Terms of Use is deemed unlawful, void or unenforceable, then that part shall be deemed severable and shall be construed in accordance with applicable law. Such a term will not affect the validity and enforceability of any remaining provisions. Hoque Global's failure to act with respect to a breach of these Terms of Use by you or others does not constitute a waiver and shall not limit Hoque Global's rights with respect to such breach or any subsequent breaches.</p>
                    </div>
                </div>
            </div>
        </section>
    <?php include "bottom.php"; ?>
</body>
</html>
